### ISSUE TITLE
Update `InfoResStatus` to match TIP-25

### ISSUE THREAD

**Issue by lzpap** [iotaledger/iota.go#344]
## Goal
Refactor info response from core api.

## Background
We have added milestoneId to the response in [InfoResStatus](https://github.com/iotaledger/iota.go/blob/d44a5388af0af5baf40d51d096c11ce40f78ce72/nodeclient/core_models.go#L29):

```yaml
    InfoResponse:
      description: Returns general information about the node.
      properties:
        name:
          type: string
          description: The name of the node.
        version:
          type: string
          description: The semantic version of the node.
        status:
          description: Status of the node.
          properties:
            isHealthy:
              type: boolean
              description: Tells whether the node is healthy or not.
            latestMilestone:
              type: object
              description: Information about the latest seen milestone.
              properties:
                index:
                  type: integer
                  description: The index of the latest seen milestone.
                timestamp:
                  type: integer
                  description: The timestamp of the latest seen milestone.
                milestoneId:
                  type: string
                  description: The Milestone ID of the latest seen milestone. Hex-encoded with 0x prefix.
              required:
                - index
                - timestamp
                - milestoneId
            confirmedMilestone:
              type: object
              description: Information about the latest confirmed milestone.
              properties:
                index:
                  type: integer
                  description: The index of the latest confirmed milestone.
                timestamp:
                  type: integer
                  description: The timestamp of the latest confirmed milestone.
                milestoneId:
                  type: string
                  description: The Milestone ID of the latest confirmed milestone. Hex-encoded with 0x prefix.
              required:
                - index
                - timestamp
                - milestoneId
```
